services:
  # Model Server (Python Flask)
  model:
    build: ./model
    image: movie-review-model:latest
    container_name: model
    networks:
      - movie

  # Backend (Java Spring Boot) - Updated to Java 21, Spring Boot 3.5
  # Database connection now points to external AWS RDS PostgreSQL
  backend:
    build: ./backend
    image: movie-review-backend:latest
    container_name: backend
    environment:
      # Database connection - Configure these to point to your AWS RDS instance
      # DB_HOST should be your RDS endpoint (e.g., movie-db.xxxxx.us-east-1.rds.amazonaws.com)
      DB_HOST: ${DB_HOST:-your-rds-endpoint.region.rds.amazonaws.com}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-moviereviews}
      DB_USERNAME: ${DB_USERNAME:-movieuser}
      DB_PASSWORD: ${DB_PASSWORD:-moviepass}
      MODEL_SERVER_URL: http://model:5000
      SERVER_PORT: 8080
    networks:
      - movie
    depends_on:
      - model

  # Frontend (React + Express) - Updated to Node 24, React 19.1
  frontend:
    build: ./frontend
    image: movie-review-frontend:latest
    container_name: frontend
    environment:
      # Backend API configuration
      BACKEND_API_URL: http://backend:8080
    networks:
      - movie
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  movie:
    driver: bridge