services:
  # Backend (Java Spring Boot) - Lambda Integration
  # Uses AWS Lambda for sentiment analysis instead of containerized model
  backend:
    build: ./backend
    image: movie-review-backend:latest
    container_name: backend
    environment:
      # Database connection - Configure these to point to your AWS RDS instance
      # DB_HOST should be your RDS endpoint (e.g., movie-db.xxxxx.region.rds.amazonaws.com)
      DB_HOST: ${DB_HOST:-your-rds-endpoint.region.rds.amazonaws.com}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-moviereviews}
      DB_USERNAME: ${DB_USERNAME:-movieuser}
      DB_PASSWORD: ${DB_PASSWORD:-moviepass}
      
      # Lambda Configuration for Sentiment Analysis
      MODEL_SERVER_MODE: lambda
      LAMBDA_FUNCTION_NAME: ${LAMBDA_FUNCTION_NAME:-movie-analyzer-sentiment}
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      LAMBDA_AUTH_METHOD: ${LAMBDA_AUTH_METHOD:-keys}  # Options: iam, keys
      
      # AWS Credentials (only needed for 'keys' authentication method)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      
      SERVER_PORT: 8080
    networks:
      - movie

  # Frontend (React + Express) - Updated to Node 24, React 19.1
  frontend:
    build: ./frontend
    image: movie-review-frontend:latest
    container_name: frontend
    environment:
      # Backend API configuration
      BACKEND_API_URL: http://backend:8080
    networks:
      - movie
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  movie:
    driver: bridge