---
# Service Account for Backend - IAM Role for Service Accounts (IRSA)
# This allows the backend to authenticate with AWS Lambda without storing credentials
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: movie-analyzer
  labels:
    app: backend
  annotations:
    # Replace ACCOUNT_ID and ROLE_NAME with your actual values
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/MovieAnalyzerBackendRole
    eks.amazonaws.com/role-arn: "REPLACE_WITH_IAM_ROLE_ARN"
automountServiceAccountToken: true 