# Default values for movie-analyzer
# This values.yaml file contains simplified parameterized configurations
# Database: Uses external AWS RDS PostgreSQL
# Sentiment Analysis: Uses AWS Lambda (serverless)

global:
  namespace: movie-analyzer

# Backend configuration - Lambda Integration
backend:
  name: backend
  replicaCount: 1
  
  image:
    repository: artisantek/movie-analyzer
    tag: backend
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  env:
    # Database connection - Configure these to point to your AWS RDS instance
    # DB_HOST should be your RDS endpoint (e.g., movie-db.xxxxx.region.rds.amazonaws.com)
    DB_HOST: "your-rds-endpoint.region.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "moviereviews"
    SERVER_PORT: "8080"
    
    # Lambda Configuration for Sentiment Analysis
    MODEL_SERVER_MODE: "lambda"
    LAMBDA_FUNCTION_NAME: "movie-analyzer-sentiment"
    AWS_REGION: "ap-south-1"
    LAMBDA_AUTH_METHOD: "iam"  # Options: iam (IAM roles), keys (access keys)
  
  # Service Account for IAM Roles for Service Accounts (IRSA)
  # Only created when using IAM authentication method
  serviceAccount:
    create: true  # Set to false if using keys authentication
    name: backend-sa
    annotations:
      # Replace with your actual IAM role ARN when using IAM method
      eks.amazonaws.com/role-arn: "REPLACE_WITH_IAM_ROLE_ARN"
  
  probes:
    readiness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    liveness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
  
  secret:
    # Base64 encoded values for RDS database credentials
    # Update these with your actual RDS username and password
    DB_USERNAME: bW92aWV1c2Vy  # movieuser (base64)
    DB_PASSWORD: bW92aWVwYXNz  # moviepass (base64)
    
    # AWS Credentials (only if not using IRSA)
    # Uncomment and configure if not using IAM roles
    # AWS_ACCESS_KEY_ID: ""
    # AWS_SECRET_ACCESS_KEY: ""

# Frontend configuration
frontend:
  name: frontend
  replicaCount: 1
  
  image:
    repository: artisantek/movie-analyzer
    tag: frontend
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  env:
    BACKEND_API_URL: "http://backend:8080"
  
  probes:
    readiness:
      path: /health
      port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      path: /health
      port: 3000
      initialDelaySeconds: 10
      periodSeconds: 10

# Ingress configuration (optional)
ingress:
  enabled: false
  host: movie.artisantek.in
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 