# Default values for movie-analyzer
# This values.yaml file contains simplified parameterized configurations
# Database: Uses external AWS RDS PostgreSQL (not containerized)

global:
  namespace: movie-analyzer

# Backend configuration
backend:
  name: backend
  replicaCount: 1
  
  image:
    repository: artisantek/movie-analyzer
    tag: backend
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  env:
    # Database connection - Configure these to point to your AWS RDS instance
    # DB_HOST should be your RDS endpoint (e.g., movie-db.xxxxx.us-east-1.rds.amazonaws.com)
    DB_HOST: "movie-analyzer-db.cnku6m4wm4rj.ap-south-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "moviereviews"
    MODEL_SERVER_URL: "http://model:5000"
    SERVER_PORT: "8080"
  
  probes:
    readiness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    liveness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
  
  secret:
    # Base64 encoded values for RDS database credentials
    # Update these with your actual RDS username and password
    DB_USERNAME: bW92aWV1c2Vy  # movieuser (base64)
    DB_PASSWORD: bW92aWVwYXNz  # moviepass (base64)

# Frontend configuration
frontend:
  name: frontend
  replicaCount: 1
  
  image:
    repository: artisantek/movie-analyzer
    tag: frontend
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  env:
    BACKEND_API_URL: "http://backend:8080"
  
  probes:
    readiness:
      path: /health
      port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      path: /health
      port: 3000
      initialDelaySeconds: 10
      periodSeconds: 10

# Model server configuration
model:
  name: model
  replicaCount: 1
  
  image:
    repository: artisantek/movie-analyzer
    tag: model
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  env:
    MODEL_PORT: "5000"
  
  probes:
    readiness:
      path: /health
      port: 5000
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      path: /health
      port: 5000
      initialDelaySeconds: 10
      periodSeconds: 10

# Ingress configuration (optional)
ingress:
  enabled: true
  # Ingress type: "alb" for AWS ALB or "nginx" for NGINX ingress controller
  type: alb  # Options: alb, nginx
  host: movie.artisantek.in
  className: alb  # Will be set to "alb" automatically when type is "alb"
  
  # ALB specific configuration
  alb:
    scheme: internet-facing
    targetType: ip
    certificateArn: arn:aws:acm:ap-south-1:879381264703:certificate/3f86f23b-ac0c-4bf2-9b4c-946e9517ccd6
    groupName: shared-alb
    groupOrder: '10'
  
  # TLS configuration (mainly for NGINX ingress)
  tls:
    enabled: false
    secretName: movie-tls-secret
  
  # Custom annotations (will be added in addition to the default ones based on type)
  customAnnotations: {}
    # Example:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"