---
# Backend Deployment - Lambda Integration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      {{- if and .Values.backend.serviceAccount.create (eq .Values.backend.env.LAMBDA_AUTH_METHOD "iam") }}
      serviceAccountName: {{ .Values.backend.serviceAccount.name }}
      {{- end }}
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        env:
        # Database Configuration
        - name: DB_HOST
          value: {{ .Values.backend.env.DB_HOST | quote }}
        - name: DB_PORT
          value: {{ .Values.backend.env.DB_PORT | quote }}
        - name: DB_NAME
          value: {{ .Values.backend.env.DB_NAME | quote }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secret
              key: DB_PASSWORD
        
        # Lambda Configuration
        - name: MODEL_SERVER_MODE
          value: {{ .Values.backend.env.MODEL_SERVER_MODE | quote }}
        - name: LAMBDA_FUNCTION_NAME
          value: {{ .Values.backend.env.LAMBDA_FUNCTION_NAME | quote }}
        - name: LAMBDA_REGION
          value: {{ .Values.backend.env.AWS_REGION | quote }}
        - name: LAMBDA_AUTH_METHOD
          value: {{ .Values.backend.env.LAMBDA_AUTH_METHOD | quote }}
        - name: LAMBDA_TIMEOUT
          value: "30000"
        
        # AWS Credentials (only if not using IRSA)
        {{- if .Values.backend.secret.AWS_ACCESS_KEY_ID }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secret
              key: AWS_ACCESS_KEY_ID
        {{- end }}
        {{- if .Values.backend.secret.AWS_SECRET_ACCESS_KEY }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secret
              key: AWS_SECRET_ACCESS_KEY
        {{- end }}
        
        - name: SERVER_PORT
          value: {{ .Values.backend.env.SERVER_PORT | quote }}
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory }}
            cpu: {{ .Values.backend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory }}
            cpu: {{ .Values.backend.resources.limits.cpu }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.probes.readiness.path }}
            port: {{ .Values.backend.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.probes.liveness.path }}
            port: {{ .Values.backend.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }} 