---
# Secret for backend application credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: {{ .Values.backend.secret.DB_USERNAME }}
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD }}
  
  # AWS credentials (only if not using IRSA)
  {{- if .Values.backend.secret.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.secret.AWS_ACCESS_KEY_ID }}
  {{- end }}
  {{- if .Values.backend.secret.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.secret.AWS_SECRET_ACCESS_KEY }}
  {{- end }} 