{{- if and .Values.backend.serviceAccount.create (eq .Values.backend.env.LAMBDA_AUTH_METHOD "iam") -}}
---
# Service Account for Backend - IAM Role for Service Accounts (IRSA)
# Only created when using IAM authentication method
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
  annotations:
    {{- with .Values.backend.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }} 